import 'package:flutter/material.dart';

class DuaColor {
  static const Color primaryColorLight100 = Color(0xFF417360);
  static const Color primaryColorLight90 = Color(0xFF4A7765);
  static const Color primaryColorLight80 = Color(0xFF5D8675);
  static const Color primaryColorLight70 = Color(0xFF709484);
  static const Color primaryColorLight60 = Color(0xFF83A394);
  static const Color primaryColorLight50 = Color(0xFF95B1A3);
  static const Color primaryColorLight40 = Color(0xFFABC0B2);
  static const Color primaryColorLight30 = Color(0xFFBBCEC2);
  static const Color primaryColorLight20 = Color(0xFFCEDDD1);
  static const Color primaryColorLight10 = Color(0xFFE1EBE1);
  static const Color primaryColorLight05 = Color(0xFFEBF2E8);
  static const Color primaryColorLight01 = Color(0xFFF2F9EF);
  static const Color subtitleColorLight = Color(0xFF686D69);
  static const Color titleColorLight = Color(0xFF282E29);
  static const Color logoTextColorLight = Color(0xFF282E29);
  static const Color sectionTextColorLight = Color(0xFF282E29);
  static const Color btnTextColorLight = Color(0xFFFBFFFB);
  static const Color headingTextColorLight = Color(0xFF282E29);
  static const Color gradientTopLight = Color(0xFFE8F5E9);
  static const Color gradientBottom1Light = Color(0xFFE8F5E9);
  static const Color gradientBottom3Light = Color(0xFFE8F5E9);
  static const Color gradientBottom2Light = Color(0xFFFBFFFB);
  static const Color backgroundColorLight = Color(0xFFFBFFFB);
  static const Color background10ColorLight = Color(0xFFFBFFFB);
  static const Color mosqueTopLight = Color(0xFFD4E9CE);
  static const Color cloudLight = Color(0xFFFFFFFF);
  static const Color cardBackgroundColorLight = Color(0xFFFFFFFF);
  static const Color cardBackColorLight1 = Color(0xFFB0CC83);
  static const Color cardBackColorLight2 = Color(0xFF8BB462);
  static const Color navbarBGColorLight = Color(0xFFFBFFFB);
  static const Color tabBtnColorLight = Color(0xFFF8FFF8);
  static const Color shadeColorLight = Color(0xFFEEF6EB);
  static const Color iconShadeColorLight = Color(0xFFD8E7D3);
  static const Color whiteColorLight = Color(0xFFFFFFFF);
  static const Color secondaryColorLight = Color(0xFFB5DDA8);
  static const Color secondaryColorLight10 = Color(0xFFB5DDA8);
  static const Color quickAccessColorLight1 = Color(0x264989E9);
  static const Color quickAccessColorLight2 = Color(0x26FF9F00);
  static const Color quickAccessColorLight3 = Color(0x262C9E4B);
  static const Color quickAccessColorLight4 = Color(0x26C36839);
  static const Color quickAccessColorLight5 = Color(0x263E9D81);
  static const Color quickAccessColorLight6 = Color(0x268459EC);
  static const Color quickAccessColorLight7 = Color(0x26277BC0);
  static const Color quickAccessColorLight8 = Color(0x26E0144C);
}
